# Generated by Django 6.0.5 on 2026-05-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechSpecialists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('competition', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_app.equipmentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('Roles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_app.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('Administrators_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_app.administrators')),
                ('TechSpecialists_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_app.techspecialists')),
                ('Users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='TicketEquipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_app.equipments')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='system_app.tickets')),
            ],
            options={
                'unique_together': {('ticket', 'equipment')},
            },
        ),
    ]
