# Generated by Django 6.0.5 on 2026-05-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
