# Generated by Django 6.0.5 on 2026-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_tickets_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentstatus',
            name='status_name',
            field=models.CharField(max_length=50),
        ),
    ]
